// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: proto/datasync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMessage_SyncType int32

const (
	SyncMessage_UNKNOWN     SyncMessage_SyncType = 0
	SyncMessage_FULL        SyncMessage_SyncType = 1
	SyncMessage_INCREMENTAL SyncMessage_SyncType = 2
	SyncMessage_DELETE      SyncMessage_SyncType = 3
	SyncMessage_HEARTBEAT   SyncMessage_SyncType = 4
)

// Enum value maps for SyncMessage_SyncType.
var (
	SyncMessage_SyncType_name = map[int32]string{
		0: "UNKNOWN",
		1: "FULL",
		2: "INCREMENTAL",
		3: "DELETE",
		4: "HEARTBEAT",
	}
	SyncMessage_SyncType_value = map[string]int32{
		"UNKNOWN":     0,
		"FULL":        1,
		"INCREMENTAL": 2,
		"DELETE":      3,
		"HEARTBEAT":   4,
	}
)

func (x SyncMessage_SyncType) Enum() *SyncMessage_SyncType {
	p := new(SyncMessage_SyncType)
	*p = x
	return p
}

func (x SyncMessage_SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMessage_SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[0].Descriptor()
}

func (SyncMessage_SyncType) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[0]
}

func (x SyncMessage_SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMessage_SyncType.Descriptor instead.
func (SyncMessage_SyncType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{2, 0}
}

type RaftMessage_MessageType int32

const (
	RaftMessage_UNKNOWN  RaftMessage_MessageType = 0
	RaftMessage_ENTRY    RaftMessage_MessageType = 1
	RaftMessage_SNAPSHOT RaftMessage_MessageType = 2
	RaftMessage_CONFIG   RaftMessage_MessageType = 3
)

// Enum value maps for RaftMessage_MessageType.
var (
	RaftMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENTRY",
		2: "SNAPSHOT",
		3: "CONFIG",
	}
	RaftMessage_MessageType_value = map[string]int32{
		"UNKNOWN":  0,
		"ENTRY":    1,
		"SNAPSHOT": 2,
		"CONFIG":   3,
	}
)

func (x RaftMessage_MessageType) Enum() *RaftMessage_MessageType {
	p := new(RaftMessage_MessageType)
	*p = x
	return p
}

func (x RaftMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[1].Descriptor()
}

func (RaftMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[1]
}

func (x RaftMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftMessage_MessageType.Descriptor instead.
func (RaftMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{6, 0}
}

type DiscoveryMessage_MessageType int32

const (
	DiscoveryMessage_UNKNOWN   DiscoveryMessage_MessageType = 0
	DiscoveryMessage_JOIN      DiscoveryMessage_MessageType = 1
	DiscoveryMessage_LEAVE     DiscoveryMessage_MessageType = 2
	DiscoveryMessage_HEARTBEAT DiscoveryMessage_MessageType = 3
	DiscoveryMessage_QUERY     DiscoveryMessage_MessageType = 4
	DiscoveryMessage_RESPONSE  DiscoveryMessage_MessageType = 5
)

// Enum value maps for DiscoveryMessage_MessageType.
var (
	DiscoveryMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "JOIN",
		2: "LEAVE",
		3: "HEARTBEAT",
		4: "QUERY",
		5: "RESPONSE",
	}
	DiscoveryMessage_MessageType_value = map[string]int32{
		"UNKNOWN":   0,
		"JOIN":      1,
		"LEAVE":     2,
		"HEARTBEAT": 3,
		"QUERY":     4,
		"RESPONSE":  5,
	}
)

func (x DiscoveryMessage_MessageType) Enum() *DiscoveryMessage_MessageType {
	p := new(DiscoveryMessage_MessageType)
	*p = x
	return p
}

func (x DiscoveryMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[2].Descriptor()
}

func (DiscoveryMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[2]
}

func (x DiscoveryMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryMessage_MessageType.Descriptor instead.
func (DiscoveryMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{7, 0}
}

type AuthMessage_MessageType int32

const (
	AuthMessage_UNKNOWN       AuthMessage_MessageType = 0
	AuthMessage_AUTHENTICATE  AuthMessage_MessageType = 1
	AuthMessage_AUTH_RESPONSE AuthMessage_MessageType = 2
	AuthMessage_CHALLENGE     AuthMessage_MessageType = 3
)

// Enum value maps for AuthMessage_MessageType.
var (
	AuthMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "AUTHENTICATE",
		2: "AUTH_RESPONSE",
		3: "CHALLENGE",
	}
	AuthMessage_MessageType_value = map[string]int32{
		"UNKNOWN":       0,
		"AUTHENTICATE":  1,
		"AUTH_RESPONSE": 2,
		"CHALLENGE":     3,
	}
)

func (x AuthMessage_MessageType) Enum() *AuthMessage_MessageType {
	p := new(AuthMessage_MessageType)
	*p = x
	return p
}

func (x AuthMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[3].Descriptor()
}

func (AuthMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[3]
}

func (x AuthMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMessage_MessageType.Descriptor instead.
func (AuthMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{10, 0}
}

type ConfigChange_ChangeType int32

const (
	ConfigChange_UNKNOWN      ConfigChange_ChangeType = 0
	ConfigChange_ADD_NODE     ConfigChange_ChangeType = 1
	ConfigChange_REMOVE_NODE  ConfigChange_ChangeType = 2
	ConfigChange_UPDATE_GROUP ConfigChange_ChangeType = 3
	ConfigChange_UPDATE_SYNC  ConfigChange_ChangeType = 4
)

// Enum value maps for ConfigChange_ChangeType.
var (
	ConfigChange_ChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADD_NODE",
		2: "REMOVE_NODE",
		3: "UPDATE_GROUP",
		4: "UPDATE_SYNC",
	}
	ConfigChange_ChangeType_value = map[string]int32{
		"UNKNOWN":      0,
		"ADD_NODE":     1,
		"REMOVE_NODE":  2,
		"UPDATE_GROUP": 3,
		"UPDATE_SYNC":  4,
	}
)

func (x ConfigChange_ChangeType) Enum() *ConfigChange_ChangeType {
	p := new(ConfigChange_ChangeType)
	*p = x
	return p
}

func (x ConfigChange_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigChange_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[4].Descriptor()
}

func (ConfigChange_ChangeType) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[4]
}

func (x ConfigChange_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigChange_ChangeType.Descriptor instead.
func (ConfigChange_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{11, 0}
}

type SyncConfig_Direction int32

const (
	SyncConfig_UNKNOWN       SyncConfig_Direction = 0
	SyncConfig_OUTBOUND      SyncConfig_Direction = 1
	SyncConfig_INBOUND       SyncConfig_Direction = 2
	SyncConfig_BIDIRECTIONAL SyncConfig_Direction = 3
)

// Enum value maps for SyncConfig_Direction.
var (
	SyncConfig_Direction_name = map[int32]string{
		0: "UNKNOWN",
		1: "OUTBOUND",
		2: "INBOUND",
		3: "BIDIRECTIONAL",
	}
	SyncConfig_Direction_value = map[string]int32{
		"UNKNOWN":       0,
		"OUTBOUND":      1,
		"INBOUND":       2,
		"BIDIRECTIONAL": 3,
	}
)

func (x SyncConfig_Direction) Enum() *SyncConfig_Direction {
	p := new(SyncConfig_Direction)
	*p = x
	return p
}

func (x SyncConfig_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncConfig_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datasync_proto_enumTypes[5].Descriptor()
}

func (SyncConfig_Direction) Type() protoreflect.EnumType {
	return &file_proto_datasync_proto_enumTypes[5]
}

func (x SyncConfig_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncConfig_Direction.Descriptor instead.
func (SyncConfig_Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{12, 0}
}

// Envelope 传输协议信封
// 所有消息都应该包装在 Envelope 中传输
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 信封版本，用于协议升级
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 发送者信息
	SourceNode  string `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	SourceGroup string `protobuf:"bytes,3,opt,name=source_group,json=sourceGroup,proto3" json:"source_group,omitempty"`
	// 目标信息
	TargetGroup string `protobuf:"bytes,4,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	// 认证令牌（由框架层统一处理）
	AuthToken string `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// 消息时间戳
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 消息ID，用于追踪和去重
	MessageId string `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// 实际的负载消息
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_SyncMessage
	//	*Envelope_SyncRequest
	//	*Envelope_SyncResponse
	//	*Envelope_RaftMessage
	//	*Envelope_DiscoveryMessage
	//	*Envelope_AuthMessage
	//	*Envelope_ConfigChange
	//	*Envelope_SnapshotData
	//	*Envelope_Heartbeat
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_datasync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *Envelope) GetSourceGroup() string {
	if x != nil {
		return x.SourceGroup
	}
	return ""
}

func (x *Envelope) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *Envelope) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSyncMessage() *SyncMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncMessage); ok {
			return x.SyncMessage
		}
	}
	return nil
}

func (x *Envelope) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Envelope) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

func (x *Envelope) GetRaftMessage() *RaftMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RaftMessage); ok {
			return x.RaftMessage
		}
	}
	return nil
}

func (x *Envelope) GetDiscoveryMessage() *DiscoveryMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DiscoveryMessage); ok {
			return x.DiscoveryMessage
		}
	}
	return nil
}

func (x *Envelope) GetAuthMessage() *AuthMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthMessage); ok {
			return x.AuthMessage
		}
	}
	return nil
}

func (x *Envelope) GetConfigChange() *ConfigChange {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConfigChange); ok {
			return x.ConfigChange
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotData() *SnapshotData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SnapshotData); ok {
			return x.SnapshotData
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_SyncMessage struct {
	SyncMessage *SyncMessage `protobuf:"bytes,10,opt,name=sync_message,json=syncMessage,proto3,oneof"`
}

type Envelope_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,11,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Envelope_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,12,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type Envelope_RaftMessage struct {
	RaftMessage *RaftMessage `protobuf:"bytes,13,opt,name=raft_message,json=raftMessage,proto3,oneof"`
}

type Envelope_DiscoveryMessage struct {
	DiscoveryMessage *DiscoveryMessage `protobuf:"bytes,14,opt,name=discovery_message,json=discoveryMessage,proto3,oneof"`
}

type Envelope_AuthMessage struct {
	AuthMessage *AuthMessage `protobuf:"bytes,15,opt,name=auth_message,json=authMessage,proto3,oneof"`
}

type Envelope_ConfigChange struct {
	ConfigChange *ConfigChange `protobuf:"bytes,16,opt,name=config_change,json=configChange,proto3,oneof"`
}

type Envelope_SnapshotData struct {
	SnapshotData *SnapshotData `protobuf:"bytes,17,opt,name=snapshot_data,json=snapshotData,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	// 心跳消息
	Heartbeat *Heartbeat `protobuf:"bytes,18,opt,name=heartbeat,proto3,oneof"`
}

func (*Envelope_SyncMessage) isEnvelope_Payload() {}

func (*Envelope_SyncRequest) isEnvelope_Payload() {}

func (*Envelope_SyncResponse) isEnvelope_Payload() {}

func (*Envelope_RaftMessage) isEnvelope_Payload() {}

func (*Envelope_DiscoveryMessage) isEnvelope_Payload() {}

func (*Envelope_AuthMessage) isEnvelope_Payload() {}

func (*Envelope_ConfigChange) isEnvelope_Payload() {}

func (*Envelope_SnapshotData) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

// Heartbeat 心跳消息
type Heartbeat struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeId  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GroupId string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 节点状态
	IsLeader bool `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// 统计信息
	ProcessedMessages uint64 `protobuf:"varint,4,opt,name=processed_messages,json=processedMessages,proto3" json:"processed_messages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_datasync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Heartbeat) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *Heartbeat) GetProcessedMessages() uint64 {
	if x != nil {
		return x.ProcessedMessages
	}
	return 0
}

// SyncMessage 同步消息
type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 注意：source_node/source_group 已移到 Envelope
	MessageId string               `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Type      SyncMessage_SyncType `protobuf:"varint,2,opt,name=type,proto3,enum=raftsync.SyncMessage_SyncType" json:"type,omitempty"`
	Records   []*DataRecord        `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	// 用于全量同步的分页
	Cursor        string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore       bool   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_proto_datasync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SyncMessage) GetType() SyncMessage_SyncType {
	if x != nil {
		return x.Type
	}
	return SyncMessage_UNKNOWN
}

func (x *SyncMessage) GetRecords() []*DataRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SyncMessage) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncMessage) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// SyncRequest 同步请求
type SyncRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SyncType  SyncMessage_SyncType   `protobuf:"varint,2,opt,name=sync_type,json=syncType,proto3,enum=raftsync.SyncMessage_SyncType" json:"sync_type,omitempty"`
	DataTypes []string               `protobuf:"bytes,3,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"`
	// 增量同步的时间戳
	Since *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	// 分页游标
	Cursor        string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_datasync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRequest) GetSyncType() SyncMessage_SyncType {
	if x != nil {
		return x.SyncType
	}
	return SyncMessage_UNKNOWN
}

func (x *SyncRequest) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *SyncRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *SyncRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SyncResponse 同步响应
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Records       []*DataRecord          `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_datasync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SyncResponse) GetRecords() []*DataRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SyncResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// DataRecord 数据记录
type DataRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRecord) Reset() {
	*x = DataRecord{}
	mi := &file_proto_datasync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRecord) ProtoMessage() {}

func (x *DataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRecord.ProtoReflect.Descriptor instead.
func (*DataRecord) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{5}
}

func (x *DataRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RaftMessage Raft 消息封装
type RaftMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          RaftMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=raftsync.RaftMessage_MessageType" json:"type,omitempty"`
	Data          []byte                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Term          uint64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_proto_datasync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{6}
}

func (x *RaftMessage) GetType() RaftMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return RaftMessage_UNKNOWN
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// DiscoveryMessage 节点发现消息
type DiscoveryMessage struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          DiscoveryMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=raftsync.DiscoveryMessage_MessageType" json:"type,omitempty"`
	Node          *NodeInfo                    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Nodes         []*NodeInfo                  `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryMessage) Reset() {
	*x = DiscoveryMessage{}
	mi := &file_proto_datasync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryMessage) ProtoMessage() {}

func (x *DiscoveryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryMessage.ProtoReflect.Descriptor instead.
func (*DiscoveryMessage) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoveryMessage) GetType() DiscoveryMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return DiscoveryMessage_UNKNOWN
}

func (x *DiscoveryMessage) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *DiscoveryMessage) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// NodeInfo 节点信息
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_datasync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{8}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *NodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NodeInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// NodeGroupInfo 节点组信息
type NodeGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	NodeIds       []string               `protobuf:"bytes,4,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	OutboundSyncs []string               `protobuf:"bytes,5,rep,name=outbound_syncs,json=outboundSyncs,proto3" json:"outbound_syncs,omitempty"`
	InboundSyncs  []string               `protobuf:"bytes,6,rep,name=inbound_syncs,json=inboundSyncs,proto3" json:"inbound_syncs,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeGroupInfo) Reset() {
	*x = NodeGroupInfo{}
	mi := &file_proto_datasync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeGroupInfo) ProtoMessage() {}

func (x *NodeGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeGroupInfo.ProtoReflect.Descriptor instead.
func (*NodeGroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{9}
}

func (x *NodeGroupInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeGroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeGroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NodeGroupInfo) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *NodeGroupInfo) GetOutboundSyncs() []string {
	if x != nil {
		return x.OutboundSyncs
	}
	return nil
}

func (x *NodeGroupInfo) GetInboundSyncs() []string {
	if x != nil {
		return x.InboundSyncs
	}
	return nil
}

func (x *NodeGroupInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeGroupInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NodeGroupInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AuthMessage 认证消息
type AuthMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          AuthMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=raftsync.AuthMessage_MessageType" json:"type,omitempty"`
	NodeId        string                  `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                  `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Certificate   []byte                  `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Success       bool                    `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                  `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_proto_datasync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{10}
}

func (x *AuthMessage) GetType() AuthMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return AuthMessage_UNKNOWN
}

func (x *AuthMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthMessage) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *AuthMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ConfigChange 配置变更
type ConfigChange struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          ConfigChange_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=raftsync.ConfigChange_ChangeType" json:"type,omitempty"`
	Node          *NodeInfo               `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Group         *NodeGroupInfo          `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	SyncConfig    *SyncConfig             `protobuf:"bytes,4,opt,name=sync_config,json=syncConfig,proto3" json:"sync_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChange) Reset() {
	*x = ConfigChange{}
	mi := &file_proto_datasync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChange) ProtoMessage() {}

func (x *ConfigChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChange.ProtoReflect.Descriptor instead.
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigChange) GetType() ConfigChange_ChangeType {
	if x != nil {
		return x.Type
	}
	return ConfigChange_UNKNOWN
}

func (x *ConfigChange) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ConfigChange) GetGroup() *NodeGroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *ConfigChange) GetSyncConfig() *SyncConfig {
	if x != nil {
		return x.SyncConfig
	}
	return nil
}

// SyncConfig 同步配置
type SyncConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceGroup   string                 `protobuf:"bytes,1,opt,name=source_group,json=sourceGroup,proto3" json:"source_group,omitempty"`
	TargetGroup   string                 `protobuf:"bytes,2,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Direction     SyncConfig_Direction   `protobuf:"varint,3,opt,name=direction,proto3,enum=raftsync.SyncConfig_Direction" json:"direction,omitempty"`
	Filter        *SyncFilter            `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfig) Reset() {
	*x = SyncConfig{}
	mi := &file_proto_datasync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfig) ProtoMessage() {}

func (x *SyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfig.ProtoReflect.Descriptor instead.
func (*SyncConfig) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{12}
}

func (x *SyncConfig) GetSourceGroup() string {
	if x != nil {
		return x.SourceGroup
	}
	return ""
}

func (x *SyncConfig) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *SyncConfig) GetDirection() SyncConfig_Direction {
	if x != nil {
		return x.Direction
	}
	return SyncConfig_UNKNOWN
}

func (x *SyncConfig) GetFilter() *SyncFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SyncConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SyncFilter 同步过滤器
type SyncFilter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataTypes        []string               `protobuf:"bytes,1,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"`
	ExcludeDataTypes []string               `protobuf:"bytes,2,rep,name=exclude_data_types,json=excludeDataTypes,proto3" json:"exclude_data_types,omitempty"`
	CustomFilter     map[string]string      `protobuf:"bytes,3,rep,name=custom_filter,json=customFilter,proto3" json:"custom_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncFilter) Reset() {
	*x = SyncFilter{}
	mi := &file_proto_datasync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilter) ProtoMessage() {}

func (x *SyncFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilter.ProtoReflect.Descriptor instead.
func (*SyncFilter) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{13}
}

func (x *SyncFilter) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *SyncFilter) GetExcludeDataTypes() []string {
	if x != nil {
		return x.ExcludeDataTypes
	}
	return nil
}

func (x *SyncFilter) GetCustomFilter() map[string]string {
	if x != nil {
		return x.CustomFilter
	}
	return nil
}

// SnapshotData 快照数据
type SnapshotData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Records       []*DataRecord          `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotData) Reset() {
	*x = SnapshotData{}
	mi := &file_proto_datasync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotData) ProtoMessage() {}

func (x *SnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datasync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotData.ProtoReflect.Descriptor instead.
func (*SnapshotData) Descriptor() ([]byte, []int) {
	return file_proto_datasync_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotData) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SnapshotData) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SnapshotData) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotData) GetRecords() []*DataRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SnapshotData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_datasync_proto protoreflect.FileDescriptor

const file_proto_datasync_proto_rawDesc = "" +
	"\n" +
	"\x14proto/datasync.proto\x12\braftsync\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x06\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12!\n" +
	"\fsource_group\x18\x03 \x01(\tR\vsourceGroup\x12!\n" +
	"\ftarget_group\x18\x04 \x01(\tR\vtargetGroup\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12:\n" +
	"\fsync_message\x18\n" +
	" \x01(\v2\x15.raftsync.SyncMessageH\x00R\vsyncMessage\x12:\n" +
	"\fsync_request\x18\v \x01(\v2\x15.raftsync.SyncRequestH\x00R\vsyncRequest\x12=\n" +
	"\rsync_response\x18\f \x01(\v2\x16.raftsync.SyncResponseH\x00R\fsyncResponse\x12:\n" +
	"\fraft_message\x18\r \x01(\v2\x15.raftsync.RaftMessageH\x00R\vraftMessage\x12I\n" +
	"\x11discovery_message\x18\x0e \x01(\v2\x1a.raftsync.DiscoveryMessageH\x00R\x10discoveryMessage\x12:\n" +
	"\fauth_message\x18\x0f \x01(\v2\x15.raftsync.AuthMessageH\x00R\vauthMessage\x12=\n" +
	"\rconfig_change\x18\x10 \x01(\v2\x16.raftsync.ConfigChangeH\x00R\fconfigChange\x12=\n" +
	"\rsnapshot_data\x18\x11 \x01(\v2\x16.raftsync.SnapshotDataH\x00R\fsnapshotData\x123\n" +
	"\theartbeat\x18\x12 \x01(\v2\x13.raftsync.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x8b\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12-\n" +
	"\x12processed_messages\x18\x04 \x01(\x04R\x11processedMessages\"\x92\x02\n" +
	"\vSyncMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.raftsync.SyncMessage.SyncTypeR\x04type\x12.\n" +
	"\arecords\x18\x03 \x03(\v2\x14.raftsync.DataRecordR\arecords\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"M\n" +
	"\bSyncType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04FULL\x10\x01\x12\x0f\n" +
	"\vINCREMENTAL\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\r\n" +
	"\tHEARTBEAT\x10\x04\"\xe8\x01\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\tsync_type\x18\x02 \x01(\x0e2\x1e.raftsync.SyncMessage.SyncTypeR\bsyncType\x12\x1d\n" +
	"\n" +
	"data_types\x18\x03 \x03(\tR\tdataTypes\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xcf\x01\n" +
	"\fSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12.\n" +
	"\arecords\x18\x04 \x03(\v2\x14.raftsync.DataRecordR\arecords\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\bR\ahasMore\"\x9b\x02\n" +
	"\n" +
	"DataRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12>\n" +
	"\bmetadata\x18\x06 \x03(\v2\".raftsync.DataRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\vRaftMessage\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.raftsync.RaftMessage.MessageTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x04R\x05index\"?\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ENTRY\x10\x01\x12\f\n" +
	"\bSNAPSHOT\x10\x02\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x03\"\xf9\x01\n" +
	"\x10DiscoveryMessage\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.raftsync.DiscoveryMessage.MessageTypeR\x04type\x12&\n" +
	"\x04node\x18\x02 \x01(\v2\x12.raftsync.NodeInfoR\x04node\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.raftsync.NodeInfoR\x05nodes\"W\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\t\n" +
	"\x05QUERY\x10\x04\x12\f\n" +
	"\bRESPONSE\x10\x05\"\xc0\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .raftsync.NodeInfo.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x03\n" +
	"\rNodeGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bnode_ids\x18\x04 \x03(\tR\anodeIds\x12%\n" +
	"\x0eoutbound_syncs\x18\x05 \x03(\tR\routboundSyncs\x12#\n" +
	"\rinbound_syncs\x18\x06 \x03(\tR\finboundSyncs\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.raftsync.NodeGroupInfo.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\vAuthMessage\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.raftsync.AuthMessage.MessageTypeR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12 \n" +
	"\vcertificate\x18\x04 \x01(\fR\vcertificate\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"N\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fAUTHENTICATE\x10\x01\x12\x11\n" +
	"\rAUTH_RESPONSE\x10\x02\x12\r\n" +
	"\tCHALLENGE\x10\x03\"\xb0\x02\n" +
	"\fConfigChange\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.raftsync.ConfigChange.ChangeTypeR\x04type\x12&\n" +
	"\x04node\x18\x02 \x01(\v2\x12.raftsync.NodeInfoR\x04node\x12-\n" +
	"\x05group\x18\x03 \x01(\v2\x17.raftsync.NodeGroupInfoR\x05group\x125\n" +
	"\vsync_config\x18\x04 \x01(\v2\x14.raftsync.SyncConfigR\n" +
	"syncConfig\"[\n" +
	"\n" +
	"ChangeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bADD_NODE\x10\x01\x12\x0f\n" +
	"\vREMOVE_NODE\x10\x02\x12\x10\n" +
	"\fUPDATE_GROUP\x10\x03\x12\x0f\n" +
	"\vUPDATE_SYNC\x10\x04\"\xa0\x02\n" +
	"\n" +
	"SyncConfig\x12!\n" +
	"\fsource_group\x18\x01 \x01(\tR\vsourceGroup\x12!\n" +
	"\ftarget_group\x18\x02 \x01(\tR\vtargetGroup\x12<\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1e.raftsync.SyncConfig.DirectionR\tdirection\x12,\n" +
	"\x06filter\x18\x04 \x01(\v2\x14.raftsync.SyncFilterR\x06filter\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"F\n" +
	"\tDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bOUTBOUND\x10\x01\x12\v\n" +
	"\aINBOUND\x10\x02\x12\x11\n" +
	"\rBIDIRECTIONAL\x10\x03\"\xe7\x01\n" +
	"\n" +
	"SyncFilter\x12\x1d\n" +
	"\n" +
	"data_types\x18\x01 \x03(\tR\tdataTypes\x12,\n" +
	"\x12exclude_data_types\x18\x02 \x03(\tR\x10excludeDataTypes\x12K\n" +
	"\rcustom_filter\x18\x03 \x03(\v2&.raftsync.SyncFilter.CustomFilterEntryR\fcustomFilter\x1a?\n" +
	"\x11CustomFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\fSnapshotData\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x04R\x05index\x12.\n" +
	"\arecords\x18\x04 \x03(\v2\x14.raftsync.DataRecordR\arecords\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.raftsync.SnapshotData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\"Z github.com/joy999/datasync/protob\x06proto3"

var (
	file_proto_datasync_proto_rawDescOnce sync.Once
	file_proto_datasync_proto_rawDescData []byte
)

func file_proto_datasync_proto_rawDescGZIP() []byte {
	file_proto_datasync_proto_rawDescOnce.Do(func() {
		file_proto_datasync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datasync_proto_rawDesc), len(file_proto_datasync_proto_rawDesc)))
	})
	return file_proto_datasync_proto_rawDescData
}

var file_proto_datasync_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_datasync_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_datasync_proto_goTypes = []any{
	(SyncMessage_SyncType)(0),         // 0: raftsync.SyncMessage.SyncType
	(RaftMessage_MessageType)(0),      // 1: raftsync.RaftMessage.MessageType
	(DiscoveryMessage_MessageType)(0), // 2: raftsync.DiscoveryMessage.MessageType
	(AuthMessage_MessageType)(0),      // 3: raftsync.AuthMessage.MessageType
	(ConfigChange_ChangeType)(0),      // 4: raftsync.ConfigChange.ChangeType
	(SyncConfig_Direction)(0),         // 5: raftsync.SyncConfig.Direction
	(*Envelope)(nil),                  // 6: raftsync.Envelope
	(*Heartbeat)(nil),                 // 7: raftsync.Heartbeat
	(*SyncMessage)(nil),               // 8: raftsync.SyncMessage
	(*SyncRequest)(nil),               // 9: raftsync.SyncRequest
	(*SyncResponse)(nil),              // 10: raftsync.SyncResponse
	(*DataRecord)(nil),                // 11: raftsync.DataRecord
	(*RaftMessage)(nil),               // 12: raftsync.RaftMessage
	(*DiscoveryMessage)(nil),          // 13: raftsync.DiscoveryMessage
	(*NodeInfo)(nil),                  // 14: raftsync.NodeInfo
	(*NodeGroupInfo)(nil),             // 15: raftsync.NodeGroupInfo
	(*AuthMessage)(nil),               // 16: raftsync.AuthMessage
	(*ConfigChange)(nil),              // 17: raftsync.ConfigChange
	(*SyncConfig)(nil),                // 18: raftsync.SyncConfig
	(*SyncFilter)(nil),                // 19: raftsync.SyncFilter
	(*SnapshotData)(nil),              // 20: raftsync.SnapshotData
	nil,                               // 21: raftsync.DataRecord.MetadataEntry
	nil,                               // 22: raftsync.NodeInfo.MetadataEntry
	nil,                               // 23: raftsync.NodeGroupInfo.MetadataEntry
	nil,                               // 24: raftsync.SyncFilter.CustomFilterEntry
	nil,                               // 25: raftsync.SnapshotData.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_proto_datasync_proto_depIdxs = []int32{
	26, // 0: raftsync.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 1: raftsync.Envelope.sync_message:type_name -> raftsync.SyncMessage
	9,  // 2: raftsync.Envelope.sync_request:type_name -> raftsync.SyncRequest
	10, // 3: raftsync.Envelope.sync_response:type_name -> raftsync.SyncResponse
	12, // 4: raftsync.Envelope.raft_message:type_name -> raftsync.RaftMessage
	13, // 5: raftsync.Envelope.discovery_message:type_name -> raftsync.DiscoveryMessage
	16, // 6: raftsync.Envelope.auth_message:type_name -> raftsync.AuthMessage
	17, // 7: raftsync.Envelope.config_change:type_name -> raftsync.ConfigChange
	20, // 8: raftsync.Envelope.snapshot_data:type_name -> raftsync.SnapshotData
	7,  // 9: raftsync.Envelope.heartbeat:type_name -> raftsync.Heartbeat
	0,  // 10: raftsync.SyncMessage.type:type_name -> raftsync.SyncMessage.SyncType
	11, // 11: raftsync.SyncMessage.records:type_name -> raftsync.DataRecord
	0,  // 12: raftsync.SyncRequest.sync_type:type_name -> raftsync.SyncMessage.SyncType
	26, // 13: raftsync.SyncRequest.since:type_name -> google.protobuf.Timestamp
	11, // 14: raftsync.SyncResponse.records:type_name -> raftsync.DataRecord
	26, // 15: raftsync.DataRecord.timestamp:type_name -> google.protobuf.Timestamp
	21, // 16: raftsync.DataRecord.metadata:type_name -> raftsync.DataRecord.MetadataEntry
	1,  // 17: raftsync.RaftMessage.type:type_name -> raftsync.RaftMessage.MessageType
	2,  // 18: raftsync.DiscoveryMessage.type:type_name -> raftsync.DiscoveryMessage.MessageType
	14, // 19: raftsync.DiscoveryMessage.node:type_name -> raftsync.NodeInfo
	14, // 20: raftsync.DiscoveryMessage.nodes:type_name -> raftsync.NodeInfo
	22, // 21: raftsync.NodeInfo.metadata:type_name -> raftsync.NodeInfo.MetadataEntry
	26, // 22: raftsync.NodeInfo.created_at:type_name -> google.protobuf.Timestamp
	26, // 23: raftsync.NodeInfo.updated_at:type_name -> google.protobuf.Timestamp
	23, // 24: raftsync.NodeGroupInfo.metadata:type_name -> raftsync.NodeGroupInfo.MetadataEntry
	26, // 25: raftsync.NodeGroupInfo.created_at:type_name -> google.protobuf.Timestamp
	26, // 26: raftsync.NodeGroupInfo.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 27: raftsync.AuthMessage.type:type_name -> raftsync.AuthMessage.MessageType
	4,  // 28: raftsync.ConfigChange.type:type_name -> raftsync.ConfigChange.ChangeType
	14, // 29: raftsync.ConfigChange.node:type_name -> raftsync.NodeInfo
	15, // 30: raftsync.ConfigChange.group:type_name -> raftsync.NodeGroupInfo
	18, // 31: raftsync.ConfigChange.sync_config:type_name -> raftsync.SyncConfig
	5,  // 32: raftsync.SyncConfig.direction:type_name -> raftsync.SyncConfig.Direction
	19, // 33: raftsync.SyncConfig.filter:type_name -> raftsync.SyncFilter
	24, // 34: raftsync.SyncFilter.custom_filter:type_name -> raftsync.SyncFilter.CustomFilterEntry
	11, // 35: raftsync.SnapshotData.records:type_name -> raftsync.DataRecord
	25, // 36: raftsync.SnapshotData.metadata:type_name -> raftsync.SnapshotData.MetadataEntry
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_proto_datasync_proto_init() }
func file_proto_datasync_proto_init() {
	if File_proto_datasync_proto != nil {
		return
	}
	file_proto_datasync_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_SyncMessage)(nil),
		(*Envelope_SyncRequest)(nil),
		(*Envelope_SyncResponse)(nil),
		(*Envelope_RaftMessage)(nil),
		(*Envelope_DiscoveryMessage)(nil),
		(*Envelope_AuthMessage)(nil),
		(*Envelope_ConfigChange)(nil),
		(*Envelope_SnapshotData)(nil),
		(*Envelope_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datasync_proto_rawDesc), len(file_proto_datasync_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_datasync_proto_goTypes,
		DependencyIndexes: file_proto_datasync_proto_depIdxs,
		EnumInfos:         file_proto_datasync_proto_enumTypes,
		MessageInfos:      file_proto_datasync_proto_msgTypes,
	}.Build()
	File_proto_datasync_proto = out.File
	file_proto_datasync_proto_goTypes = nil
	file_proto_datasync_proto_depIdxs = nil
}
